Added solution task 'arrays'
lengenkon/study pull request #2
Opened 2022-08-03 18:14 UTC by lengenkon

2022-08-04 17:49 UTC, NickelGit requested changes

2022-08-04 17:49 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if item > max }
лучше вынести поиск максимума в отдельный метод т.к. велика вероятность что он может быть переиспользован в дальнейшем

2022-08-04 17:49 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        array.each { |item| new_array << (item.positive? ? max : item) }
в данном случае лучше использовать `.map` т.к. он по результату работы вернет новый массив, что освобождает нас от необходимости создавать для нового массива отдельную переменную

2022-08-04 17:49 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +      def search(array1, query)
зачем в конце имени массива нужна `1`?

2022-08-04 17:49 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        -1
1) Что такое `l`, `f` и `m`? Пожалуйста дай переменным названия объясняющие их назначение.
2) Давай попробуем переписать метод используя рекурсию, для удобства можно использовать параметры со значениями по умолчанию ( https://medium.com/@sologoubalex/parameters-with-default-values-in-ruby-74cd0e830681 )
3) Для облегчения читаемости лучше сократить количество последовательных условий (if-elsif-else)  и разделить это на несколько проверок:
  - Проверка что нужный элемент массива найден
  - Тернарная операция определяющая в какой части массива нужно искать дальше

2022-08-08 18:16 UTC, lengenkon commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if item > max }
Я исправила замечания, создала новый коммит, возможно, вы не увидели. На вкладке Files changed можно увидеть изменения.

2022-08-11 15:32 UTC, NickelGit requested changes

2022-08-11 15:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        my_max = ->(item) { max = item if item > max }
Пожалуйста вынеси поиск максимума в отдельный метод.Например:
```
def max(array)
  ...
end
```

2022-08-11 15:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
>          array
Это кажется тут лишнее, `array.map! { ... }` возвращает как раз то что нам нужно, новый массив с замененными числами. Отдельно возвращать `array` не нужно.

2022-08-11 15:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
эти значения можно задавать сразу как дефолтные в параметрах метода

2022-08-11 15:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        else
вложенность ухудшает читаемость, лучше представить это в виде guard clause
https://anthonygharvey.com/guard-clauses-vs-nested-conditionals

И давай в нем же сразу проверим не только что мы ничего не нашли в конце поиска, но и то имеет ли нам смысл вообще что то искать дальше. 
Мы знаем что массив отсортирован, и что в начале у него самое маленькое значение, а в конце самое большое. (Что в т.ч. справедливо и для любого подмассива).
Т.е. мы можем проверить входит ли то число которое мы ищем в рамки того массива(или подмассива) в котором мы собираемся искать.

2022-08-11 15:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +            middle
Это так же лучше представить в виде guard clause

2022-08-11 15:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +          end
В данном случае вместо `if-elseif-else` лучше использовать тернарную операцию
https://www.rubyguides.com/2019/10/ruby-ternary-operator/

2022-08-11 15:33 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if item > max }
Не все замечания были исправлены, поэтому не сразу заметил что были внесены изменения. В новых комментариях к коду описал чуть более подробно.

2022-08-24 11:45 UTC, lengenkon commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if item > max }
Я изучила все замечания, исправила, но наткнулась на ошибку линтера: Method definitions must not be nested. Use lambda instead.

2022-08-24 11:55 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if item > max }
Все верно, метод `max` не должен быть `nested`, его не нужно объявлять внутри метода `replace`. Метод max надо вынести в отдельный метод.

Должно быть примерно так:
```
def replace(array)
  ...
  max = max(array)
  ...
end

def max(array)
  ...your code...
end
```

2022-08-24 12:15 UTC, lengenkon commented on test/exercise/arrays/solution.rb
> +        array.each { |item| max = item if item > max }
Точно, поняла, спасибо. Исправила.

2022-08-24 13:46 UTC, NickelGit requested changes

2022-08-24 13:46 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        array.map! { |item| item.positive? ? my_max(array) : item }
лучше сначала найти максимальное с использованием my_max и записать его в переменную, а уже потом эту переменную использовать в цикле.
Т.к. сейчас нам на каждой итерации цикла придется еще раз проходить по всему массиву и заново искать max.

```
max = my_max(array)
array.map! { |item| item.positive? ? max : item }
```

2022-08-24 13:46 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        return -1 if first > last && query > last
Давай еще добавим проверку что число которое мы ищем не меньше самого маленького, в этом случае тоже нет смысла дальше искать.

2022-08-25 11:06 UTC, lengenkon commented on test/exercise/arrays/solution.rb
> +        return -1 if first > last && query > last
Да, забыла, исправила.

2022-08-26 11:06 UTC, merged